# Generated by Django 3.1.7 on 2021-08-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='space',
            name='coordinates',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='space',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterModelTable(
            name='space',
            table='Space',
        ),
    ]
